const db = require('./src/config/db');

async function run() {
  try {
    await db.initialize();
    
    const tables = [
      { name: 'DOI_TAC', col: 'MADOITAC', start: 1000 },
      { name: 'NHANVIEN', col: 'MANHANVIEN', start: 1000 },
      { name: 'SAN_PHAM', col: 'MASANPHAM', start: 1000 },
      { name: 'DON_HANG', col: 'MADONHANG', start: 1000 },
      { name: 'CHI_TIET_DON_HANG', col: 'MACHITIET', start: 1000 },
      { name: 'VAI_TRO', col: 'MAVAITRO', start: 1000 },
      { name: 'PHIEU_LUONG', col: 'MAPHIEU', start: 1000 },
      { name: 'CHAM_CONG', col: 'MACHAMCONG', start: 1000 },
      { name: 'HOA_DON_NHAP_HANG', col: 'MAHOADONNHAP', start: 1000 },
      { name: 'CHI_TIET_HOA_DON_NHAP', col: 'MACHITIET', start: 1000 },
      { name: 'KIEM_KE', col: 'MAKIEMKE', start: 1000 },
      { name: 'CHI_TIET_KIEM_KE', col: 'MACHITIET', start: 1000 },
      { name: 'HO_SO_THU_CUNG', col: 'MATHUCUNG', start: 1000 }
    ];

    for (const t of tables) {
      try {
        console.log(`Resetting sequence for table ${t.name}...`);
        await db.query(`ALTER TABLE ${t.name} MODIFY (${t.col} GENERATED BY DEFAULT AS IDENTITY (START WITH ${t.start}))`);
        console.log(`Successfully reset sequence for table ${t.name}`);
      } catch (e) {
        console.error(`Failed to reset table ${t.name}:`, e.message);
      }
    }

  } catch (err) {
    console.error('ERROR:', err);
  } finally {
    await db.close();
  }
}

run();
